# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

additionalRepositories:
  # Syntax: <repo-url>@<branch or commit>:<destination-folder>
  - https://github.com/eyaler/hebrew_tokenizer.git@main:/hebrew_tokenizer

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: install requirements
    init: pip3 install -r requirements.txt

#  - name: install tokenizer
#    init: git clone https://github.com/eyaler/hebrew_tokenizer.git
#
#additionalRepositories:
#  - url:


